# Generated by Django 3.2 on 2023-02-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20230201_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Role'),
        ),
    ]
