# Generated by Django 3.2 on 2023-01-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20230126_0945'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personfilmwork',
            table='content"."person_film_work',
        ),
    ]
