# Generated by Django 3.2 on 2023-01-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_personfilmwork_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='content"."person',
        ),
    ]
