# Generated by Django 3.2 on 2023-02-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_personfilmwork_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(blank=True, choices=[('MOV', 'movie'), ('TVS', 'tv_show')], max_length=30, verbose_name='type'),
        ),
    ]
