# Generated by Django 3.2 on 2023-01-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_person_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(max_length=255, null=True, verbose_name='role'),
        ),
    ]
