# Generated by Django 3.2 on 2023-01-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_personfilmwork_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=1981, verbose_name='Creation_date'),
            preserve_default=False,
        ),
    ]
